//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvanceTourismGuide.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ATGSEntities1 : DbContext
    {
        public ATGSEntities1()
            : base("name=ATGSEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminInfo> AdminInfoes { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<Place> Places { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<Map> Maps { get; set; }
        public virtual DbSet<Guide> Guides { get; set; }
        public virtual DbSet<Hotel> Hotels { get; set; }
        public virtual DbSet<Vehical> Vehicals { get; set; }
        public virtual DbSet<GuideBooking> GuideBookings { get; set; }
        public virtual DbSet<Hotel_Booking> Hotel_Booking { get; set; }
        public virtual DbSet<VehicalBooking> VehicalBookings { get; set; }
        public virtual DbSet<Cost_Estimation> Cost_Estimation { get; set; }
    }
}
