//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvanceTourismGuide.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guide
    {
        public int Guide_Id { get; set; }
        public int Place_Id { get; set; }
        public string Guide_Name { get; set; }
        public string Guide_Address { get; set; }
        public string Guide_Pic { get; set; }
        public string Guide_Contac { get; set; }
    }
}
