//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvanceTourismGuide.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuideBooking
    {
        public int GB_Id { get; set; }
        public int Place_Id { get; set; }
        public string User_name { get; set; }
        public string Phone { get; set; }
        public string Approve_Status { get; set; }
        public string GB_Comment { get; set; }
    }
}
