//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvanceTourismGuide.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Map
    {
        public int Map_Id { get; set; }
        public int Place_Id { get; set; }
        public string Long { get; set; }
        public string Lat { get; set; }
    }
}
