//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvanceTourismGuide.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehical
    {
        public int Vehicale_id { get; set; }
        public int Place_Id { get; set; }
        public string Vehical_Name { get; set; }
        public string Vehical_Address { get; set; }
        public string Vehical_Pic { get; set; }
        public string Vehical_dis { get; set; }
        public string Vehical_Contact { get; set; }
    }
}
